

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
    types: [opened, synchronize]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  build-and-deploy:
    needs: [avoid_reduncy]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

    #   # Install Composer dependencies
    #   - name: Install Composer Dependencies
    #     run: composer install --no-dev --optimize-autoloader
        # Install Node.js dependencies
      - name: Install Node.js Dependencies
        run: npm i
    #   # Build assets with Yarn
      - name: Build Assets
        run: npm run build
      - name: Archive Build Output
        run: zip -r build.zip . -x ".github" "package.json" "gulpfile.js" "README.md" ".gitignore" ".vite.config.js" "node_modules" "pnpm-lock.yaml" ".env"

      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          password: ${{ secrets.STAGING_PASS }}
          port: ${{ secrets.STAGING_PORT }}
          source: "build.zip"
          target: "/tmp"

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          password: ${{ secrets.STAGING_PASS }}
          port: ${{ secrets.STAGING_PORT }}
          script: |
            rm -rf ${{ secrets.STAGING_DEPLOY_PATH }}
            unzip /tmp/build.zip -d /tmp/build
            mkdir -p ${{ secrets.STAGING_DEPLOY_PATH }}
            mv /tmp/build/* ${{ secrets.STAGING_DEPLOY_PATH }}
            rm -rf /tmp/build
            rm /tmp/build.zip